# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(236, 203)
        MainWindow.setStyleSheet("background-color: #22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clickB = QtWidgets.QPushButton(self.centralwidget)
        self.clickB.setGeometry(QtCore.QRect(70, 70, 91, 91))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setBold(True)
        font.setWeight(75)
        self.clickB.setFont(font)
        self.clickB.setStyleSheet("QPushButton{\n"
                                  "    color: white;\n"
                                  "    border: 2px solid #ee52ff;\n"
                                  "    background-color: #11111e;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed{\n"
                                  "    color: white;\n"
                                  "    background-color: #00000e;\n"
                                  "    border: 2px solid #94349e\n"
                                  "}\n"
                                  "")
        self.clickB.setObjectName("clickB")
        self.count = QtWidgets.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(80, 30, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setBold(True)
        font.setWeight(75)
        self.count.setFont(font)
        self.count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.count.setStyleSheet("border: 2px solid #ee52ff;\n"
                                 "color: white")
        self.count.setAlignment(QtCore.Qt.AlignCenter)
        self.count.setObjectName("count")
        self.clickB_2 = QtWidgets.QPushButton(self.centralwidget)
        self.clickB_2.setGeometry(QtCore.QRect(10, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setBold(True)
        font.setWeight(75)
        self.clickB_2.setFont(font)
        self.clickB_2.setStyleSheet("QPushButton{\n"
                                    "    color: white;\n"
                                    "    border: 2px solid #ee52ff;\n"
                                    "    background-color: #11111e;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed{\n"
                                    "    color: white;\n"
                                    "    background-color: #00000e;\n"
                                    "    border: 2px solid #94349e\n"
                                    "}\n"
                                    "")
        self.clickB_2.setObjectName("clickB_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clickB.setText(_translate("MainWindow", "Click"))
        self.count.setText(_translate("MainWindow", "0"))
        self.clickB_2.setText(_translate("MainWindow", "Refresh"))
